# Generated by Django 4.1.1 on 2022-10-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_0',
            field=models.CharField(max_length=21, null=True),
        ),
    ]
