# Generated by Django 4.1.1 on 2022-10-23 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_post_preview_0'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='preview_0',
        ),
    ]
