# Generated by Django 4.1.1 on 2022-11-05 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_userssubscriptions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersSubscriptions',
        ),
    ]
